baseURL = 'https://tbird.cafe'
languageCode = 'en-us'
title = 'Tbirdcafe'
theme = 'hugo-theme-m10c'

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 2
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 3

[params]
    author = 'Tbird'
    description = 'Curious soul with a loud mind'
    avatar = 'images/pfp.png'
    menu_item_separator = " | "

# TBIRD theme
[params.style]
  darkestColor = "#1E2429"
  darkColor = "#242E34"
  lightColor = "#CAD2C5"
  lightestColor = "#FFFFFF"
  primaryColor = "#40e0d0"
  codeColor = "#8881ec"

# Default theme
# [params.style]
#   darkestColor = "#242930"
#   darkColor = "#353b43"
#   lightColor = "#afbac4"
#   lightestColor = "#ffffff"
#   primaryColor = "#57cc8a"
